### PR TITLE
[BEX-1053] - Create new bill regeneration topics on

### PR DESCRIPTION
**Pull request by agkountis**
These topics are needed to facilitate our new bill regeneration architecture.

### CODE REVIEW

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: dev-aws
Module: pubsub/kafka-shared-msk-customer-billing
Path: dev-aws/kafka-shared-msk/customer-billing
Commit ID: 6715c1ec043baa0660f264db433be500f1d5546a
Requested At: 2024-10-02T10:54:32Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan dev-aws/kafka-shared-msk/customer-billing` as comment.

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: prod-aws
Module: pubsub/kafka-shared-msk-customer-billing
Path: prod-aws/kafka-shared-msk/customer-billing
Commit ID: 6715c1ec043baa0660f264db433be500f1d5546a
Requested At: 2024-10-02T10:54:34Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan prod-aws/kafka-shared-msk/customer-billing` as comment.

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: prod-aws
Module: pubsub/kafka-shared-msk-customer-billing
Path: prod-aws/kafka-shared-msk/customer-billing
Commit ID: 6715c1ec043baa0660f264db433be500f1d5546a
Requested At: 2024-10-02T10:54:34Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan prod-aws/kafka-shared-msk/customer-billing` as comment.

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: dev-aws
Module: pubsub/kafka-shared-msk-customer-billing
Path: dev-aws/kafka-shared-msk/customer-billing
Commit ID: b992e8fcf97f8a5ad868772689bf8fb87c5b31bf
Requested At: 2024-10-02T10:56:42Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan dev-aws/kafka-shared-msk/customer-billing` as comment.

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: prod-aws
Module: pubsub/kafka-shared-msk-customer-billing
Path: prod-aws/kafka-shared-msk/customer-billing
Commit ID: b992e8fcf97f8a5ad868772689bf8fb87c5b31bf
Requested At: 2024-10-02T10:56:43Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan prod-aws/kafka-shared-msk/customer-billing` as comment.

**Review by sbuliarca — APPROVED** [review]

**Review by espang-uw — APPROVED** [review]

**Pull request merged**
