### PR TITLE
Add proximo-tls topics & groups

### PR DESCRIPTION
**Pull request by matiit**

### CODE REVIEW

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: prod-aws
Module: pubsub/kafka-shared-msk-account-identity
Path: prod-aws/kafka-shared-msk/account-identity
Commit ID: 92f201a71de75ff0a222243bf3319ed578c7a76f
Requested At: 2024-09-24T10:28:50Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan prod-aws/kafka-shared-msk/account-identity` as comment.

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: prod-aws
Module: pubsub/kafka-shared-msk-account-identity
Path: prod-aws/kafka-shared-msk/account-identity
Commit ID: 92f201a71de75ff0a222243bf3319ed578c7a76f
Requested At: 2024-09-24T10:28:50Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan prod-aws/kafka-shared-msk/account-identity` as comment.

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: prod-aws
Module: pubsub/kafka-shared-msk-account-identity
Path: prod-aws/kafka-shared-msk/account-identity
Commit ID: 92f201a71de75ff0a222243bf3319ed578c7a76f
Requested At: 2024-09-24T10:28:51Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan prod-aws/kafka-shared-msk/account-identity` as comment.

**Review by sbuliarca — APPROVED** [review]

**Review by abramin — APPROVED** [review]

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: prod-aws
Module: pubsub/kafka-shared-msk-account-identity
Path: prod-aws/kafka-shared-msk/account-identity
Commit ID: 1a6554a64dfbf62be1d2ec5d3e40388eb647a52e
Requested At: 2024-09-24T10:40:02Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan prod-aws/kafka-shared-msk/account-identity` as comment.

**Pull request merged**
