### PR TITLE
ACC-770 msk/account_identity: add di-kafka-source config for verification events

### PR DESCRIPTION
**Pull request by Jarota**

### CODE REVIEW

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: prod-aws
Module: pubsub/kafka-shared-msk-account-identity
Path: prod-aws/kafka-shared-msk/account-identity
Commit ID: 1af478960ed20f0669ad6e85cadc12e6d97264a2
Requested At: 2024-11-11T10:49:15Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan prod-aws/kafka-shared-msk/account-identity` as comment.

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: dev-aws
Module: pubsub/kafka-shared-msk-account-identity
Path: dev-aws/kafka-shared-msk/account-identity
Commit ID: 1af478960ed20f0669ad6e85cadc12e6d97264a2
Requested At: 2024-11-11T10:50:11Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan dev-aws/kafka-shared-msk/account-identity` as comment.

**Review by denisnikulin — APPROVED** [review]

**Comment by uw-infra** [comment]
Terraform run output for
```
Cluster: dev-aws
Module: pubsub/kafka-shared-msk-account-identity
Path: dev-aws/kafka-shared-msk/account-identity
Commit ID: b4c8ee2ad0c4a328d20e1855aa2a0e38b9575572
```
<details><summary><b>✅ Run Status: Ok, Run Summary: Apply complete! Resources: 2 added, 0 changed, 0 destroyed</b></summary>

```terraform

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.account_identity_di_kafka_source_verification.kafka_acl.group_acl["account-identity.di-kafka-source-verification"] will be created
  + resource "kafka_acl" "group_acl" {
      + acl_host                     = "*"
      + acl_operation                = "Read"
      + acl_permission_type          = "Allow"
      + acl_principal                = "User:CN=auth-customer/di-verification"
      + id                           = (known after apply)
      + resource_name                = "account-identity.di-kafka-source-verification"
      + resource_pattern_type_filter = "Literal"
      + resource_type                = "Group"
    }

  # module.account_identity_di_kafka_source_verification.kafka_acl.topic_acl["account-identity.verification.events.v1"] will be created
  + resource "kafka_acl" "topic_acl" {
      + acl_host                     = "*"
      + acl_operation                = "Read"
      + acl_permission_type          = "Allow"
      + acl_principal                = "User:CN=auth-customer/di-verification"
      + id                           = (known after apply)
      + resource_name                = "account-identity.verification.events.v1"
      + resource_pattern_type_filter = "Literal"
      + resource_type                = "Topic"
    }

Plan: 2 to add, 0 to change, 0 to destroy.
module.account_identity_di_kafka_source_verification.kafka_acl.group_acl["account-identity.di-kafka-source-verification"]: Creating...
module.account_identity_di_kafka_source_verification.kafka_acl.topic_acl["account-identity.verification.events.v1"]: Creating...
module.account_identity_di_kafka_source_verification.kafka_acl.group_acl["account-identity.di-kafka-source-verification"]: Creation complete after 1s [id=User:CN=auth-customer/di-verification|*|Read|Allow|Group|account-identity.di-kafka-source-verification|Literal]
module.account_identity_di_kafka_source_verification.kafka_acl.topic_acl["account-identity.verification.events.v1"]: Creation complete after 1s [id=User:CN=auth-customer/di-verification|*|Read|Allow|Topic|account-identity.verification.events.v1|Literal]

Warning: Argument is deprecated

  with provider["registry.terraform.io/mongey/kafka"],
  on __env.tf line 12, in provider "kafka":
  12: provider "kafka" {

This parameter is now deprecated and will be removed in a later release,
please use `client_cert` instead.

(and one more similar warning elsewhere)

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

```
</details>

> To manually trigger plan again please post `@terraform-applier plan dev-aws/kafka-shared-msk/account-identity` as comment.

**Comment by uw-infra** [comment]
Terraform run output for
```
Cluster: prod-aws
Module: pubsub/kafka-shared-msk-account-identity
Path: prod-aws/kafka-shared-msk/account-identity
Commit ID: b4c8ee2ad0c4a328d20e1855aa2a0e38b9575572
```
<details><summary><b>✅ Run Status: Ok, Run Summary: Apply complete! Resources: 2 added, 0 changed, 0 destroyed</b></summary>

```terraform

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.account_identity_di_kafka_source_verification.kafka_acl.group_acl["account-identity.di-kafka-source-verification"] will be created
  + resource "kafka_acl" "group_acl" {
      + acl_host                     = "*"
      + acl_operation                = "Read"
      + acl_permission_type          = "Allow"
      + acl_principal                = "User:CN=auth-customer/di-verification"
      + id                           = (known after apply)
      + resource_name                = "account-identity.di-kafka-source-verification"
      + resource_pattern_type_filter = "Literal"
      + resource_type                = "Group"
    }

  # module.account_identity_di_kafka_source_verification.kafka_acl.topic_acl["account-identity.verification.events.v1"] will be created
  + resource "kafka_acl" "topic_acl" {
      + acl_host                     = "*"
      + acl_operation                = "Read"
      + acl_permission_type          = "Allow"
      + acl_principal                = "User:CN=auth-customer/di-verification"
      + id                           = (known after apply)
      + resource_name                = "account-identity.verification.events.v1"
      + resource_pattern_type_filter = "Literal"
      + resource_type                = "Topic"
    }

Plan: 2 to add, 0 to change, 0 to destroy.
module.account_identity_di_kafka_source_verification.kafka_acl.topic_acl["account-identity.verification.events.v1"]: Creating...
module.account_identity_di_kafka_source_verification.kafka_acl.group_acl["account-identity.di-kafka-source-verification"]: Creating...
module.account_identity_di_kafka_source_verification.kafka_acl.group_acl["account-identity.di-kafka-source-verification"]: Creation complete after 1s [id=User:CN=auth-customer/di-verification|*|Read|Allow|Group|account-identity.di-kafka-source-verification|Literal]
module.account_identity_di_kafka_source_verification.kafka_acl.topic_acl["account-identity.verification.events.v1"]: Creation complete after 1s [id=User:CN=auth-customer/di-verification|*|Read|Allow|Topic|account-identity.verification.events.v1|Literal]

Warning: Argument is deprecated

  with provider["registry.terraform.io/mongey/kafka"],
  on __env.tf line 12, in provider "kafka":
  12: provider "kafka" {

This parameter is now deprecated and will be removed in a later release,
please use `client_cert` instead.

(and one more similar warning elsewhere)

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

```
</details>

> To manually trigger plan again please post `@terraform-applier plan prod-aws/kafka-shared-msk/account-identity` as comment.

**Pull request merged**
