### PR TITLE
[BEX-834] add new dlq topic for reprint events

### PR DESCRIPTION
**Pull request by espang-uw**

### CODE REVIEW

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: dev-aws
Module: pubsub/kafka-shared-msk-customer-billing
Path: dev-aws/kafka-shared-msk/customer-billing
Commit ID: 20743908fb034c8261637c1aca2ebfa03240ad04
Requested At: 2024-10-03T12:37:11Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan dev-aws/kafka-shared-msk/customer-billing` as comment.

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: prod-aws
Module: pubsub/kafka-shared-msk-customer-billing
Path: prod-aws/kafka-shared-msk/customer-billing
Commit ID: 20743908fb034c8261637c1aca2ebfa03240ad04
Requested At: 2024-10-03T12:37:12Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan prod-aws/kafka-shared-msk/customer-billing` as comment.

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: prod-aws
Module: pubsub/kafka-shared-msk-customer-billing
Path: prod-aws/kafka-shared-msk/customer-billing
Commit ID: df9cb2582b855291ef3d1fb07a30e7d87ed67d1e
Requested At: 2024-10-03T12:37:53Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan prod-aws/kafka-shared-msk/customer-billing` as comment.

**Review by mgrzebykuw — APPROVED** [review]

**Comment by sbuliarca** [comment]
We need to rebase/merge the main branch into this one, as I made a refactoring on the modules backend configuration

**Comment by espang-uw** [comment]
> We need to rebase/merge the main branch into this one, as I made a refactoring on the modules backend configuration

Done

**Review by sbuliarca — APPROVED** [review]

**Pull request merged**
