### PR TITLE
Add insurance consumer groups for proximo

### PR DESCRIPTION
**Pull request by Nesze**

### CODE REVIEW

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: dev-aws
Module: pubsub/kafka-shared-msk-account-identity
Path: dev-aws/kafka-shared-msk/account-identity
Commit ID: 9e7d5dbbe37b540d368eb64acc4b9ff5f50a3b46
Requested At: 2024-10-09T12:32:17Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan dev-aws/kafka-shared-msk/account-identity` as comment.

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: prod-aws
Module: pubsub/kafka-shared-msk-account-identity
Path: prod-aws/kafka-shared-msk/account-identity
Commit ID: 9e7d5dbbe37b540d368eb64acc4b9ff5f50a3b46
Requested At: 2024-10-09T12:32:18Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan prod-aws/kafka-shared-msk/account-identity` as comment.

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: dev-aws
Module: pubsub/kafka-shared-msk-account-identity
Path: dev-aws/kafka-shared-msk/account-identity
Commit ID: 5e71b9a4b68656d27a5658af5cd4079b3699f393
Requested At: 2024-10-09T12:35:28Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan dev-aws/kafka-shared-msk/account-identity` as comment.

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: prod-aws
Module: pubsub/kafka-shared-msk-account-identity
Path: prod-aws/kafka-shared-msk/account-identity
Commit ID: 5e71b9a4b68656d27a5658af5cd4079b3699f393
Requested At: 2024-10-09T12:35:29Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan prod-aws/kafka-shared-msk/account-identity` as comment.

**Review by pmdcosta — APPROVED** [review]

**Review by Jarota — APPROVED** [review]

**Pull request merged**
