### PR TITLE
dev-aws/msk/cbc: add missing consume topics

### PR DESCRIPTION
**Pull request by LukeG07**

### CODE REVIEW

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: prod-aws
Module: pubsub/kafka-shared-msk-cbc
Path: prod-aws/kafka-shared-msk/cbc
Commit ID: 40dbe4bbe6a76be14c5e5f92b10af28182753d34
Requested At: 2024-10-29T12:10:16Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan prod-aws/kafka-shared-msk/cbc` as comment.

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: dev-aws
Module: pubsub/kafka-shared-msk-cbc
Path: dev-aws/kafka-shared-msk/cbc
Commit ID: dd3d4bcd69d5933cd7f8b560e8de04a48042eacd
Requested At: 2024-10-29T12:10:16Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan dev-aws/kafka-shared-msk/cbc` as comment.

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: prod-aws
Module: pubsub/kafka-shared-msk-cbc
Path: prod-aws/kafka-shared-msk/cbc
Commit ID: a77f54944f8bf23b8306e23f66587aa8afa886e5
Requested At: 2024-10-29T12:19:17Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan prod-aws/kafka-shared-msk/cbc` as comment.

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: dev-aws
Module: pubsub/kafka-shared-msk-cbc
Path: dev-aws/kafka-shared-msk/cbc
Commit ID: e24edaf520c6e973e6943454b6c101d9f91b254f
Requested At: 2024-10-29T12:27:19Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan dev-aws/kafka-shared-msk/cbc` as comment.

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: dev-aws
Module: pubsub/kafka-shared-msk-cbc
Path: dev-aws/kafka-shared-msk/cbc
Commit ID: a05c4fb40cc29da41273ebb299765cda46ea5d51
Requested At: 2024-10-29T12:29:57Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan dev-aws/kafka-shared-msk/cbc` as comment.

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: dev-aws
Module: pubsub/kafka-shared-msk-cbc
Path: dev-aws/kafka-shared-msk/cbc
Commit ID: 44eab6f8d43a117b02866354a6ce9224307cb082
Requested At: 2024-10-29T12:31:43Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan dev-aws/kafka-shared-msk/cbc` as comment.

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: dev-aws
Module: pubsub/kafka-shared-msk-cbc
Path: dev-aws/kafka-shared-msk/cbc
Commit ID: 4a263033fdb9eee53ad656ad35f7a39bca85bb2d
Requested At: 2024-10-29T12:35:22Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan dev-aws/kafka-shared-msk/cbc` as comment.

**Review by martskins — APPROVED** [review]

**Comment by uw-infra** [comment]
Terraform run output for
```
Cluster: dev-aws
Module: pubsub/kafka-shared-msk-cbc
Path: dev-aws/kafka-shared-msk/cbc
Commit ID: eb25e8f83756e409948d6c79c9ed621e37649ba4
```
<details><summary><b>✅ Run Status: Ok, Run Summary: Apply complete! Resources: 2 added, 0 changed, 0 destroyed</b></summary>

```terraform

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.cbc_dispute_credits_projector.kafka_acl.topic_acl["cbc.MdesEvents"] will be created
  + resource "kafka_acl" "topic_acl" {
      + acl_host                     = "*"
      + acl_operation                = "Read"
      + acl_permission_type          = "Allow"
      + acl_principal                = "User:CN=cbc/cbc-dispute-credits-projector"
      + id                           = (known after apply)
      + resource_name                = "cbc.MdesEvents"
      + resource_pattern_type_filter = "Literal"
      + resource_type                = "Topic"
    }

  # module.cbc_mdes_projector.kafka_acl.topic_acl["cbc.RatingEvents_v3"] will be created
  + resource "kafka_acl" "topic_acl" {
      + acl_host                     = "*"
      + acl_operation                = "Read"
      + acl_permission_type          = "Allow"
      + acl_principal                = "User:CN=cbc/cbc-mdes-projector"
      + id                           = (known after apply)
      + resource_name                = "cbc.RatingEvents_v3"
      + resource_pattern_type_filter = "Literal"
      + resource_type                = "Topic"
    }

Plan: 2 to add, 0 to change, 0 to destroy.
module.cbc_mdes_projector.kafka_acl.topic_acl["cbc.RatingEvents_v3"]: Creating...
module.cbc_dispute_credits_projector.kafka_acl.topic_acl["cbc.MdesEvents"]: Creating...
module.cbc_mdes_projector.kafka_acl.topic_acl["cbc.RatingEvents_v3"]: Creation complete after 1s [id=User:CN=cbc/cbc-mdes-projector|*|Read|Allow|Topic|cbc.RatingEvents_v3|Literal]
module.cbc_dispute_credits_projector.kafka_acl.topic_acl["cbc.MdesEvents"]: Creation complete after 1s [id=User:CN=cbc/cbc-dispute-credits-projector|*|Read|Allow|Topic|cbc.MdesEvents|Literal]

Warning: Argument is deprecated

  with provider["registry.terraform.io/mongey/kafka"],
  on __env.tf line 12, in provider "kafka":
  12: provider "kafka" {

This parameter is now deprecated and will be removed in a later release,
please use `client_key` instead.

(and one more similar warning elsewhere)

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

```
</details>

> To manually trigger plan again please post `@terraform-applier plan dev-aws/kafka-shared-msk/cbc` as comment.

**Pull request merged**
