### PR TITLE
Add topic for move out notification

### PR DESCRIPTION
**Pull request by abramin**
https://github.com/utilitywarehouse/kubernetes-manifests/pull/101338

### CODE REVIEW

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: dev-aws
Module: pubsub/kafka-shared-msk-account-identity
Path: dev-aws/kafka-shared-msk/account-identity
Commit ID: d310dfb22256cd85f80b96f6e9a476e8d7144be1
Requested At: 2024-12-10T12:51:34Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan dev-aws/kafka-shared-msk/account-identity` as comment.

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: dev-aws
Module: pubsub/kafka-shared-msk-account-identity
Path: dev-aws/kafka-shared-msk/account-identity
Commit ID: 3594c9b3b3ad0098ff51285437af0f4fd6386f74
Requested At: 2024-12-10T12:57:44Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan dev-aws/kafka-shared-msk/account-identity` as comment.

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: dev-aws
Module: pubsub/kafka-shared-msk-account-identity
Path: dev-aws/kafka-shared-msk/account-identity
Commit ID: e7cc043468e5680bbe17a1a7986c4fce05ab389c
Requested At: 2024-12-10T13:04:11Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan dev-aws/kafka-shared-msk/account-identity` as comment.

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: dev-aws
Module: pubsub/kafka-shared-msk-account-identity
Path: dev-aws/kafka-shared-msk/account-identity
Commit ID: 7612d031108965a742988a87ba608a9bf7504cda
Requested At: 2024-12-10T13:12:38Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan dev-aws/kafka-shared-msk/account-identity` as comment.

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: dev-aws
Module: pubsub/kafka-shared-msk-account-identity
Path: dev-aws/kafka-shared-msk/account-identity
Commit ID: fe62c2aaf366fd1ce4937301423d6f3eff24fb39
Requested At: 2024-12-11T12:40:28Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan dev-aws/kafka-shared-msk/account-identity` as comment.

**Review by matiit — APPROVED** [review]

**Comment by uw-infra** [comment]
Terraform run output for
```
Cluster: dev-aws
Module: pubsub/kafka-shared-msk-account-identity
Path: dev-aws/kafka-shared-msk/account-identity
Commit ID: 3bb0f92915653ea8d9cebba58411c085bfff75d4
```
<details><summary><b>✅ Run Status: Ok, Run Summary: Apply complete! Resources: 3 added, 0 changed, 0 destroyed</b></summary>

```terraform

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # kafka_topic.account_identity_analytics_v1 will be created
  + resource "kafka_topic" "account_identity_analytics_v1" {
      + config             = {
          + "cleanup.policy"        = "delete"
          + "compression.type"      = "zstd"
          + "local.retention.ms"    = "86400000"
          + "remote.storage.enable" = "true"
          + "retention.ms"          = "604800000"
        }
      + id                 = (known after apply)
      + name               = "account-identity.analytics.v1"
      + partitions         = 15
      + replication_factor = 3
    }

  # module.account_identity_di_analytics.kafka_acl.group_acl["account-identity.di-kafka-source-move-out-notification"] will be created
  + resource "kafka_acl" "group_acl" {
      + acl_host                     = "*"
      + acl_operation                = "Read"
      + acl_permission_type          = "Allow"
      + acl_principal                = "User:CN=account-platform/di_analytics"
      + id                           = (known after apply)
      + resource_name                = "account-identity.di-kafka-source-move-out-notification"
      + resource_pattern_type_filter = "Literal"
      + resource_type                = "Group"
    }

  # module.account_identity_di_analytics.kafka_acl.topic_acl["account-identity.analytics.v1"] will be created
  + resource "kafka_acl" "topic_acl" {
      + acl_host                     = "*"
      + acl_operation                = "Read"
      + acl_permission_type          = "Allow"
      + acl_principal                = "User:CN=account-platform/di_analytics"
      + id                           = (known after apply)
      + resource_name                = "account-identity.analytics.v1"
      + resource_pattern_type_filter = "Literal"
      + resource_type                = "Topic"
    }

Plan: 3 to add, 0 to change, 0 to destroy.
kafka_topic.account_identity_analytics_v1: Creating...
module.account_identity_di_analytics.kafka_acl.group_acl["account-identity.di-kafka-source-move-out-notification"]: Creating...
module.account_identity_di_analytics.kafka_acl.group_acl["account-identity.di-kafka-source-move-out-notification"]: Creation complete after 1s [id=User:CN=account-platform/di_analytics|*|Read|Allow|Group|account-identity.di-kafka-source-move-out-notification|Literal]
kafka_topic.account_identity_analytics_v1: Creation complete after 1s [id=account-identity.analytics.v1]
module.account_identity_di_analytics.kafka_acl.topic_acl["account-identity.analytics.v1"]: Creating...
module.account_identity_di_analytics.kafka_acl.topic_acl["account-identity.analytics.v1"]: Creation complete after 1s [id=User:CN=account-platform/di_analytics|*|Read|Allow|Topic|account-identity.analytics.v1|Literal]

Warning: Argument is deprecated

  with provider["registry.terraform.io/mongey/kafka"],
  on __env.tf line 12, in provider "kafka":
  12: provider "kafka" {

This parameter is now deprecated and will be removed in a later release,
please use `client_cert` instead.

(and one more similar warning elsewhere)

Apply complete! Resources: 3 added, 0 changed, 0 destroyed.

```
</details>

> To manually trigger plan again please post `@terraform-applier plan dev-aws/kafka-shared-msk/account-identity` as comment.

**Pull request merged**
