### PR TITLE
FPAY-1611: Added new pq service topics for payment methods

### PR DESCRIPTION
**Pull request by rafdekar**

### CODE REVIEW

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: dev-aws
Module: pubsub/kafka-shared-msk-payment-platform
Path: dev-aws/kafka-shared-msk/payment-platform
Commit ID: 732664675cf618561172c98c250275ba5f38882c
Requested At: 2024-10-18T09:48:59Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan dev-aws/kafka-shared-msk/payment-platform` as comment.

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: prod-aws
Module: pubsub/kafka-shared-msk-payment-platform
Path: prod-aws/kafka-shared-msk/payment-platform
Commit ID: 732664675cf618561172c98c250275ba5f38882c
Requested At: 2024-10-18T09:50:42Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan prod-aws/kafka-shared-msk/payment-platform` as comment.

**Review by sbuliarca — APPROVED** [review]

**Comment by uw-infra** [comment]
Terraform run output for
```
Cluster: dev-aws
Module: pubsub/kafka-shared-msk-payment-platform
Path: dev-aws/kafka-shared-msk/payment-platform
Commit ID: 0fd8810e800119e3ce1abc4d20a934aeb780dd20
```
<details><summary><b>✅ Run Status: Ok, Run Summary: Apply complete! Resources: 3 added, 0 changed, 0 destroyed</b></summary>

```terraform

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # kafka_topic.payment_method_deadletter_v1_events will be created
  + resource "kafka_topic" "payment_method_deadletter_v1_events" {
      + config             = {
          + "cleanup.policy"        = "delete"
          + "compression.type"      = "zstd"
          + "local.retention.ms"    = "172800000"
          + "remote.storage.enable" = "true"
          + "retention.bytes"       = "-1"
          + "retention.ms"          = "2592000000"
        }
      + id                 = (known after apply)
      + name               = "payment-platform.payment-method-deadletter.v1.events"
      + partitions         = 5
      + replication_factor = 3
    }

  # module.payment_query_service.kafka_acl.producer_acl["payment-platform.payment-method-deadletter.v1.events"] will be created
  + resource "kafka_acl" "producer_acl" {
      + acl_host                     = "*"
      + acl_operation                = "Write"
      + acl_permission_type          = "Allow"
      + acl_principal                = "User:CN=payment-platform/payment-query-service"
      + id                           = (known after apply)
      + resource_name                = "payment-platform.payment-method-deadletter.v1.events"
      + resource_pattern_type_filter = "Literal"
      + resource_type                = "Topic"
    }

  # module.payment_query_service.kafka_acl.topic_acl["payment-platform.payment-method.v1.events"] will be created
  + resource "kafka_acl" "topic_acl" {
      + acl_host                     = "*"
      + acl_operation                = "Read"
      + acl_permission_type          = "Allow"
      + acl_principal                = "User:CN=payment-platform/payment-query-service"
      + id                           = (known after apply)
      + resource_name                = "payment-platform.payment-method.v1.events"
      + resource_pattern_type_filter = "Literal"
      + resource_type                = "Topic"
    }

Plan: 3 to add, 0 to change, 0 to destroy.
kafka_topic.payment_method_deadletter_v1_events: Creating...
module.payment_query_service.kafka_acl.topic_acl["payment-platform.payment-method.v1.events"]: Creating...
module.payment_query_service.kafka_acl.topic_acl["payment-platform.payment-method.v1.events"]: Creation complete after 0s [id=User:CN=payment-platform/payment-query-service|*|Read|Allow|Topic|payment-platform.payment-method.v1.events|Literal]
kafka_topic.payment_method_deadletter_v1_events: Creation complete after 1s [id=payment-platform.payment-method-deadletter.v1.events]
module.payment_query_service.kafka_acl.producer_acl["payment-platform.payment-method-deadletter.v1.events"]: Creating...
module.payment_query_service.kafka_acl.producer_acl["payment-platform.payment-method-deadletter.v1.events"]: Creation complete after 1s [id=User:CN=payment-platform/payment-query-service|*|Write|Allow|Topic|payment-platform.payment-method-deadletter.v1.events|Literal]

Warning: Argument is deprecated

  with provider["registry.terraform.io/mongey/kafka"],
  on __env.tf line 12, in provider "kafka":
  12: provider "kafka" {

This parameter is now deprecated and will be removed in a later release,
please use `client_cert` instead.

(and one more similar warning elsewhere)

Apply complete! Resources: 3 added, 0 changed, 0 destroyed.

```
</details>

> To manually trigger plan again please post `@terraform-applier plan dev-aws/kafka-shared-msk/payment-platform` as comment.

**Comment by uw-infra** [comment]
Terraform run output for
```
Cluster: prod-aws
Module: pubsub/kafka-shared-msk-payment-platform
Path: prod-aws/kafka-shared-msk/payment-platform
Commit ID: 0fd8810e800119e3ce1abc4d20a934aeb780dd20
```
<details><summary><b>✅ Run Status: Ok, Run Summary: Apply complete! Resources: 3 added, 0 changed, 0 destroyed</b></summary>

```terraform

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # kafka_topic.payment_method_deadletter_v1_events will be created
  + resource "kafka_topic" "payment_method_deadletter_v1_events" {
      + config             = {
          + "cleanup.policy"        = "delete"
          + "compression.type"      = "zstd"
          + "local.retention.ms"    = "172800000"
          + "remote.storage.enable" = "true"
          + "retention.bytes"       = "-1"
          + "retention.ms"          = "2592000000"
        }
      + id                 = (known after apply)
      + name               = "payment-platform.payment-method-deadletter.v1.events"
      + partitions         = 5
      + replication_factor = 3
    }

  # module.payment_query_service.kafka_acl.producer_acl["payment-platform.payment-method-deadletter.v1.events"] will be created
  + resource "kafka_acl" "producer_acl" {
      + acl_host                     = "*"
      + acl_operation                = "Write"
      + acl_permission_type          = "Allow"
      + acl_principal                = "User:CN=payment-platform/payment-query-service"
      + id                           = (known after apply)
      + resource_name                = "payment-platform.payment-method-deadletter.v1.events"
      + resource_pattern_type_filter = "Literal"
      + resource_type                = "Topic"
    }

  # module.payment_query_service.kafka_acl.topic_acl["payment-platform.payment-method.v1.events"] will be created
  + resource "kafka_acl" "topic_acl" {
      + acl_host                     = "*"
      + acl_operation                = "Read"
      + acl_permission_type          = "Allow"
      + acl_principal                = "User:CN=payment-platform/payment-query-service"
      + id                           = (known after apply)
      + resource_name                = "payment-platform.payment-method.v1.events"
      + resource_pattern_type_filter = "Literal"
      + resource_type                = "Topic"
    }

Plan: 3 to add, 0 to change, 0 to destroy.
kafka_topic.payment_method_deadletter_v1_events: Creating...
module.payment_query_service.kafka_acl.topic_acl["payment-platform.payment-method.v1.events"]: Creating...
module.payment_query_service.kafka_acl.topic_acl["payment-platform.payment-method.v1.events"]: Creation complete after 0s [id=User:CN=payment-platform/payment-query-service|*|Read|Allow|Topic|payment-platform.payment-method.v1.events|Literal]
kafka_topic.payment_method_deadletter_v1_events: Creation complete after 1s [id=payment-platform.payment-method-deadletter.v1.events]
module.payment_query_service.kafka_acl.producer_acl["payment-platform.payment-method-deadletter.v1.events"]: Creating...
module.payment_query_service.kafka_acl.producer_acl["payment-platform.payment-method-deadletter.v1.events"]: Creation complete after 0s [id=User:CN=payment-platform/payment-query-service|*|Write|Allow|Topic|payment-platform.payment-method-deadletter.v1.events|Literal]

Warning: Argument is deprecated

  with provider["registry.terraform.io/mongey/kafka"],
  on __env.tf line 12, in provider "kafka":
  12: provider "kafka" {

This parameter is now deprecated and will be removed in a later release,
please use `client_key` instead.

(and one more similar warning elsewhere)

Apply complete! Resources: 3 added, 0 changed, 0 destroyed.

```
</details>

> To manually trigger plan again please post `@terraform-applier plan prod-aws/kafka-shared-msk/payment-platform` as comment.

**Pull request merged**
