### PR TITLE
Added kafka topics for cards v2 architecture

### PR DESCRIPTION
**Pull request by rafdekar**

### CODE REVIEW

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: dev-aws
Module: pubsub/kafka-shared-msk-payment-platform
Path: dev-aws/kafka-shared-msk/payment-platform
Commit ID: 7a8504ecd91327c437413f504e79470103fe3b9e
Requested At: 2024-11-15T10:03:58Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan dev-aws/kafka-shared-msk/payment-platform` as comment.

**Review by tginszt — COMMENTED** [review]
are these v1 or v2 topics?
Using v1 flag for the new v2 topics could make it a bit confusing

**Comment by rafdekar** [comment]
> are these v1 or v2 topics
These are part of v2 architecture, but are v1 versions of the topics

**Comment by rafdekar** [comment]
Its more related to the proto I guess than to the architecture version

**Comment by rafdekar** [comment]
Proto for the events on the topic is going to be v1, since these events do not exist yet

**Comment by uw-infra** [comment]
Terraform run output for
```
Cluster: dev-aws
Module: pubsub/kafka-shared-msk-payment-platform
Path: dev-aws/kafka-shared-msk/payment-platform
Commit ID: a65c8cd0968ebaec628958dc88361fbf198892ac
```
<details><summary><b>✅ Run Status: Ok, Run Summary: Apply complete! Resources: 6 added, 0 changed, 0 destroyed</b></summary>

```terraform

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # kafka_topic.card_deadletter_v1_internal will be created
  + resource "kafka_topic" "card_deadletter_v1_internal" {
      + config             = {
          + "cleanup.policy"        = "delete"
          + "compression.type"      = "zstd"
          + "local.retention.ms"    = "172800000"
          + "remote.storage.enable" = "true"
          + "retention.bytes"       = "-1"
          + "retention.ms"          = "2592000000"
        }
      + id                 = (known after apply)
      + name               = "payment-platform.card-deadletter.v1.internal"
      + partitions         = 5
      + replication_factor = 3
    }

  # kafka_topic.card_deadletter_v1_internal_3ds will be created
  + resource "kafka_topic" "card_deadletter_v1_internal_3ds" {
      + config             = {
          + "cleanup.policy"        = "delete"
          + "compression.type"      = "zstd"
          + "local.retention.ms"    = "172800000"
          + "remote.storage.enable" = "true"
          + "retention.bytes"       = "-1"
          + "retention.ms"          = "2592000000"
        }
      + id                 = (known after apply)
      + name               = "payment-platform.card-deadletter.v1.internal.3ds"
      + partitions         = 5
      + replication_factor = 3
    }

  # kafka_topic.card_deadletter_v1_internal_payment_methods will be created
  + resource "kafka_topic" "card_deadletter_v1_internal_payment_methods" {
      + config             = {
          + "cleanup.policy"        = "delete"
          + "compression.type"      = "zstd"
          + "local.retention.ms"    = "172800000"
          + "remote.storage.enable" = "true"
          + "retention.bytes"       = "-1"
          + "retention.ms"          = "2592000000"
        }
      + id                 = (known after apply)
      + name               = "payment-platform.card-deadletter.v1.internal.payment-methods"
      + partitions         = 5
      + replication_factor = 3
    }

  # kafka_topic.card_v1_internal will be created
  + resource "kafka_topic" "card_v1_internal" {
      + config             = {
          + "cleanup.policy"        = "delete"
          + "compression.type"      = "zstd"
          + "local.retention.ms"    = "172800000"
          + "remote.storage.enable" = "true"
          + "retention.bytes"       = "-1"
          + "retention.ms"          = "2592000000"
        }
      + id                 = (known after apply)
      + name               = "payment-platform.card.v1.internal"
      + partitions         = 5
      + replication_factor = 3
    }

  # kafka_topic.card_v1_internal_3ds will be created
  + resource "kafka_topic" "card_v1_internal_3ds" {
      + config             = {
          + "cleanup.policy"        = "delete"
          + "compression.type"      = "zstd"
          + "local.retention.ms"    = "172800000"
          + "remote.storage.enable" = "true"
          + "retention.bytes"       = "-1"
          + "retention.ms"          = "2592000000"
        }
      + id                 = (known after apply)
      + name               = "payment-platform.card.v1.internal.3ds"
      + partitions         = 5
      + replication_factor = 3
    }

  # kafka_topic.card_v1_internal_payment_methods will be created
  + resource "kafka_topic" "card_v1_internal_payment_methods" {
      + config             = {
          + "cleanup.policy"        = "delete"
          + "compression.type"      = "zstd"
          + "local.retention.ms"    = "172800000"
          + "remote.storage.enable" = "true"
          + "retention.bytes"       = "-1"
          + "retention.ms"          = "2592000000"
        }
      + id                 = (known after apply)
      + name               = "payment-platform.card.v1.internal.payment-methods"
      + partitions         = 5
      + replication_factor = 3
    }

Plan: 6 to add, 0 to change, 0 to destroy.
kafka_topic.card_deadletter_v1_internal_3ds: Creating...
kafka_topic.card_v1_internal: Creating...
kafka_topic.card_v1_internal_3ds: Creating...
kafka_topic.card_deadletter_v1_internal_payment_methods: Creating...
kafka_topic.card_v1_internal_payment_methods: Creating...
kafka_topic.card_deadletter_v1_internal: Creating...
kafka_topic.card_deadletter_v1_internal_3ds: Creation complete after 1s [id=payment-platform.card-deadletter.v1.internal.3ds]
kafka_topic.card_v1_internal: Creation complete after 1s [id=payment-platform.card.v1.internal]
kafka_topic.card_v1_internal_3ds: Creation complete after 1s [id=payment-platform.card.v1.internal.3ds]
kafka_topic.card_deadletter_v1_internal_payment_methods: Creation complete after 2s [id=payment-platform.card-deadletter.v1.internal.payment-methods]
kafka_topic.card_deadletter_v1_internal: Creation complete after 2s [id=payment-platform.card-deadletter.v1.internal]
kafka_topic.card_v1_internal_payment_methods: Creation complete after 2s [id=payment-platform.card.v1.internal.payment-methods]

Warning: Argument is deprecated

  with provider["registry.terraform.io/mongey/kafka"],
  on __env.tf line 12, in provider "kafka":
  12: provider "kafka" {

This parameter is now deprecated and will be removed in a later release,
please use `client_cert` instead.

(and one more similar warning elsewhere)

Apply complete! Resources: 6 added, 0 changed, 0 destroyed.

```
</details>

> To manually trigger plan again please post `@terraform-applier plan dev-aws/kafka-shared-msk/payment-platform` as comment.

**Pull request merged**
