### PR TITLE
add missing dsar producers and consumers

### PR DESCRIPTION
**Pull request by alvaro-marting**

### CODE REVIEW

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: dev-aws
Module: pubsub/kafka-shared-msk-contact-channels
Path: dev-aws/kafka-shared-msk/contact-channels
Commit ID: 1137730c491c59e81460d04a439f104d7833e2c1
Requested At: 2024-11-13T14:16:08Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan dev-aws/kafka-shared-msk/contact-channels` as comment.

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: prod-aws
Module: pubsub/kafka-shared-msk-contact-channels
Path: prod-aws/kafka-shared-msk/contact-channels
Commit ID: 1137730c491c59e81460d04a439f104d7833e2c1
Requested At: 2024-11-13T14:16:08Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan prod-aws/kafka-shared-msk/contact-channels` as comment.

**Review by tmus — APPROVED** [review]

**Comment by uw-infra** [comment]
Terraform run output for
```
Cluster: prod-aws
Module: pubsub/kafka-shared-msk-contact-channels
Path: prod-aws/kafka-shared-msk/contact-channels
Commit ID: 202844a06088e8251192225a4dd75c1aa3e90ffc
```
<details><summary><b>✅ Run Status: Ok, Run Summary: Apply complete! Resources: 6 added, 0 changed, 0 destroyed</b></summary>

```terraform

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.dsar_conversations_retriever.kafka_acl.group_acl["contact-channels.dsar-conversations-retriever"] will be created
  + resource "kafka_acl" "group_acl" {
      + acl_host                     = "*"
      + acl_operation                = "Read"
      + acl_permission_type          = "Allow"
      + acl_principal                = "User:CN=contact-channels/dsar-conversations-retriever"
      + id                           = (known after apply)
      + resource_name                = "contact-channels.dsar-conversations-retriever"
      + resource_pattern_type_filter = "Literal"
      + resource_type                = "Group"
    }

  # module.dsar_conversations_retriever.kafka_acl.topic_acl["contact-channels.dsar_conversation"] will be created
  + resource "kafka_acl" "topic_acl" {
      + acl_host                     = "*"
      + acl_operation                = "Read"
      + acl_permission_type          = "Allow"
      + acl_principal                = "User:CN=contact-channels/dsar-conversations-retriever"
      + id                           = (known after apply)
      + resource_name                = "contact-channels.dsar_conversation"
      + resource_pattern_type_filter = "Literal"
      + resource_type                = "Topic"
    }

  # module.dsar_job_fulfiller.kafka_acl.group_acl["contact-channels.dsar-job-fulfiller"] will be created
  + resource "kafka_acl" "group_acl" {
      + acl_host                     = "*"
      + acl_operation                = "Read"
      + acl_permission_type          = "Allow"
      + acl_principal                = "User:CN=contact-channels/dsar-job-fulfiller"
      + id                           = (known after apply)
      + resource_name                = "contact-channels.dsar-job-fulfiller"
      + resource_pattern_type_filter = "Literal"
      + resource_type                = "Group"
    }

  # module.dsar_job_fulfiller.kafka_acl.topic_acl["contact-channels.dsar_job"] will be created
  + resource "kafka_acl" "topic_acl" {
      + acl_host                     = "*"
      + acl_operation                = "Read"
      + acl_permission_type          = "Allow"
      + acl_principal                = "User:CN=contact-channels/dsar-job-fulfiller"
      + id                           = (known after apply)
      + resource_name                = "contact-channels.dsar_job"
      + resource_pattern_type_filter = "Literal"
      + resource_type                = "Topic"
    }

  # module.dsar_job_request_producer.kafka_acl.producer_acl["contact-channels.dsar_conversation"] will be created
  + resource "kafka_acl" "producer_acl" {
      + acl_host                     = "*"
      + acl_operation                = "Write"
      + acl_permission_type          = "Allow"
      + acl_principal                = "User:CN=contact-channels/dsar-job-runner"
      + id                           = (known after apply)
      + resource_name                = "contact-channels.dsar_conversation"
      + resource_pattern_type_filter = "Literal"
      + resource_type                = "Topic"
    }

  # module.dsar_job_request_producer.kafka_acl.producer_acl["contact-channels.dsar_job"] will be created
  + resource "kafka_acl" "producer_acl" {
      + acl_host                     = "*"
      + acl_operation                = "Write"
      + acl_permission_type          = "Allow"
      + acl_principal                = "User:CN=contact-channels/dsar-job-runner"
      + id                           = (known after apply)
      + resource_name                = "contact-channels.dsar_job"
      + resource_pattern_type_filter = "Literal"
      + resource_type                = "Topic"
    }

Plan: 6 to add, 0 to change, 0 to destroy.
module.dsar_job_fulfiller.kafka_acl.group_acl["contact-channels.dsar-job-fulfiller"]: Creating...
module.dsar_conversations_retriever.kafka_acl.topic_acl["contact-channels.dsar_conversation"]: Creating...
module.dsar_job_fulfiller.kafka_acl.topic_acl["contact-channels.dsar_job"]: Creating...
module.dsar_job_request_producer.kafka_acl.producer_acl["contact-channels.dsar_job"]: Creating...
module.dsar_conversations_retriever.kafka_acl.group_acl["contact-channels.dsar-conversations-retriever"]: Creating...
module.dsar_job_request_producer.kafka_acl.producer_acl["contact-channels.dsar_conversation"]: Creating...
module.dsar_conversations_retriever.kafka_acl.topic_acl["contact-channels.dsar_conversation"]: Creation complete after 1s [id=User:CN=contact-channels/dsar-conversations-retriever|*|Read|Allow|Topic|contact-channels.dsar_conversation|Literal]
module.dsar_conversations_retriever.kafka_acl.group_acl["contact-channels.dsar-conversations-retriever"]: Creation complete after 1s [id=User:CN=contact-channels/dsar-conversations-retriever|*|Read|Allow|Group|contact-channels.dsar-conversations-retriever|Literal]
module.dsar_job_fulfiller.kafka_acl.topic_acl["contact-channels.dsar_job"]: Creation complete after 1s [id=User:CN=contact-channels/dsar-job-fulfiller|*|Read|Allow|Topic|contact-channels.dsar_job|Literal]
module.dsar_job_request_producer.kafka_acl.producer_acl["contact-channels.dsar_conversation"]: Creation complete after 1s [id=User:CN=contact-channels/dsar-job-runner|*|Write|Allow|Topic|contact-channels.dsar_conversation|Literal]
module.dsar_job_request_producer.kafka_acl.producer_acl["contact-channels.dsar_job"]: Creation complete after 1s [id=User:CN=contact-channels/dsar-job-runner|*|Write|Allow|Topic|contact-channels.dsar_job|Literal]
module.dsar_job_fulfiller.kafka_acl.group_acl["contact-channels.dsar-job-fulfiller"]: Creation complete after 1s [id=User:CN=contact-channels/dsar-job-fulfiller|*|Read|Allow|Group|contact-channels.dsar-job-fulfiller|Literal]

Warning: Argument is deprecated

  with provider["registry.terraform.io/mongey/kafka"],
  on __env.tf line 12, in provider "kafka":
  12: provider "kafka" {

This parameter is now deprecated and will be removed in a later release,
please use `client_cert` instead.

(and one more similar warning elsewhere)

Apply complete! Resources: 6 added, 0 changed, 0 destroyed.

```
</details>

> To manually trigger plan again please post `@terraform-applier plan prod-aws/kafka-shared-msk/contact-channels` as comment.

**Comment by uw-infra** [comment]
Terraform run output for
```
Cluster: dev-aws
Module: pubsub/kafka-shared-msk-contact-channels
Path: dev-aws/kafka-shared-msk/contact-channels
Commit ID: 202844a06088e8251192225a4dd75c1aa3e90ffc
```
<details><summary><b>✅ Run Status: Ok, Run Summary: Apply complete! Resources: 6 added, 0 changed, 0 destroyed</b></summary>

```terraform

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.dsar_conversations_retriever.kafka_acl.group_acl["contact-channels.dsar-conversations-retriever"] will be created
  + resource "kafka_acl" "group_acl" {
      + acl_host                     = "*"
      + acl_operation                = "Read"
      + acl_permission_type          = "Allow"
      + acl_principal                = "User:CN=contact-channels/dsar-conversations-retriever"
      + id                           = (known after apply)
      + resource_name                = "contact-channels.dsar-conversations-retriever"
      + resource_pattern_type_filter = "Literal"
      + resource_type                = "Group"
    }

  # module.dsar_conversations_retriever.kafka_acl.topic_acl["contact-channels.dsar_conversation"] will be created
  + resource "kafka_acl" "topic_acl" {
      + acl_host                     = "*"
      + acl_operation                = "Read"
      + acl_permission_type          = "Allow"
      + acl_principal                = "User:CN=contact-channels/dsar-conversations-retriever"
      + id                           = (known after apply)
      + resource_name                = "contact-channels.dsar_conversation"
      + resource_pattern_type_filter = "Literal"
      + resource_type                = "Topic"
    }

  # module.dsar_job_fulfiller.kafka_acl.group_acl["contact-channels.dsar-job-fulfiller"] will be created
  + resource "kafka_acl" "group_acl" {
      + acl_host                     = "*"
      + acl_operation                = "Read"
      + acl_permission_type          = "Allow"
      + acl_principal                = "User:CN=contact-channels/dsar-job-fulfiller"
      + id                           = (known after apply)
      + resource_name                = "contact-channels.dsar-job-fulfiller"
      + resource_pattern_type_filter = "Literal"
      + resource_type                = "Group"
    }

  # module.dsar_job_fulfiller.kafka_acl.topic_acl["contact-channels.dsar_job"] will be created
  + resource "kafka_acl" "topic_acl" {
      + acl_host                     = "*"
      + acl_operation                = "Read"
      + acl_permission_type          = "Allow"
      + acl_principal                = "User:CN=contact-channels/dsar-job-fulfiller"
      + id                           = (known after apply)
      + resource_name                = "contact-channels.dsar_job"
      + resource_pattern_type_filter = "Literal"
      + resource_type                = "Topic"
    }

  # module.dsar_job_request_producer.kafka_acl.producer_acl["contact-channels.dsar_conversation"] will be created
  + resource "kafka_acl" "producer_acl" {
      + acl_host                     = "*"
      + acl_operation                = "Write"
      + acl_permission_type          = "Allow"
      + acl_principal                = "User:CN=contact-channels/dsar-job-runner"
      + id                           = (known after apply)
      + resource_name                = "contact-channels.dsar_conversation"
      + resource_pattern_type_filter = "Literal"
      + resource_type                = "Topic"
    }

  # module.dsar_job_request_producer.kafka_acl.producer_acl["contact-channels.dsar_job"] will be created
  + resource "kafka_acl" "producer_acl" {
      + acl_host                     = "*"
      + acl_operation                = "Write"
      + acl_permission_type          = "Allow"
      + acl_principal                = "User:CN=contact-channels/dsar-job-runner"
      + id                           = (known after apply)
      + resource_name                = "contact-channels.dsar_job"
      + resource_pattern_type_filter = "Literal"
      + resource_type                = "Topic"
    }

Plan: 6 to add, 0 to change, 0 to destroy.
module.dsar_job_fulfiller.kafka_acl.group_acl["contact-channels.dsar-job-fulfiller"]: Creating...
module.dsar_conversations_retriever.kafka_acl.topic_acl["contact-channels.dsar_conversation"]: Creating...
module.dsar_job_request_producer.kafka_acl.producer_acl["contact-channels.dsar_job"]: Creating...
module.dsar_conversations_retriever.kafka_acl.group_acl["contact-channels.dsar-conversations-retriever"]: Creating...
module.dsar_job_fulfiller.kafka_acl.topic_acl["contact-channels.dsar_job"]: Creating...
module.dsar_job_request_producer.kafka_acl.producer_acl["contact-channels.dsar_conversation"]: Creating...
module.dsar_conversations_retriever.kafka_acl.group_acl["contact-channels.dsar-conversations-retriever"]: Creation complete after 0s [id=User:CN=contact-channels/dsar-conversations-retriever|*|Read|Allow|Group|contact-channels.dsar-conversations-retriever|Literal]
module.dsar_conversations_retriever.kafka_acl.topic_acl["contact-channels.dsar_conversation"]: Creation complete after 0s [id=User:CN=contact-channels/dsar-conversations-retriever|*|Read|Allow|Topic|contact-channels.dsar_conversation|Literal]
module.dsar_job_fulfiller.kafka_acl.group_acl["contact-channels.dsar-job-fulfiller"]: Creation complete after 0s [id=User:CN=contact-channels/dsar-job-fulfiller|*|Read|Allow|Group|contact-channels.dsar-job-fulfiller|Literal]
module.dsar_job_request_producer.kafka_acl.producer_acl["contact-channels.dsar_job"]: Creation complete after 0s [id=User:CN=contact-channels/dsar-job-runner|*|Write|Allow|Topic|contact-channels.dsar_job|Literal]
module.dsar_job_request_producer.kafka_acl.producer_acl["contact-channels.dsar_conversation"]: Creation complete after 0s [id=User:CN=contact-channels/dsar-job-runner|*|Write|Allow|Topic|contact-channels.dsar_conversation|Literal]
module.dsar_job_fulfiller.kafka_acl.topic_acl["contact-channels.dsar_job"]: Creation complete after 0s [id=User:CN=contact-channels/dsar-job-fulfiller|*|Read|Allow|Topic|contact-channels.dsar_job|Literal]

Warning: Argument is deprecated

  with provider["registry.terraform.io/mongey/kafka"],
  on __env.tf line 12, in provider "kafka":
  12: provider "kafka" {

This parameter is now deprecated and will be removed in a later release,
please use `client_key` instead.

(and one more similar warning elsewhere)

Apply complete! Resources: 6 added, 0 changed, 0 destroyed.

```
</details>

> To manually trigger plan again please post `@terraform-applier plan dev-aws/kafka-shared-msk/contact-channels` as comment.

**Pull request merged**
