### PR TITLE
ACC-770 msk/account-identity: fix verification di kafka source config

### PR DESCRIPTION
**Pull request by Jarota**
On autopilot before and had it consuming from the wrong topic

### CODE REVIEW

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: prod-aws
Module: pubsub/kafka-shared-msk-account-identity
Path: prod-aws/kafka-shared-msk/account-identity
Commit ID: 021f1842d8083d5ec40ae0670a1ea7268239707e
Requested At: 2024-11-11T12:49:15Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan prod-aws/kafka-shared-msk/account-identity` as comment.

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: prod-aws
Module: pubsub/kafka-shared-msk-iam
Path: prod-aws/kafka-shared-msk/iam
Commit ID: 021f1842d8083d5ec40ae0670a1ea7268239707e
Requested At: 2024-11-11T12:49:16Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan prod-aws/kafka-shared-msk/iam` as comment.

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: dev-aws
Module: pubsub/kafka-shared-msk-iam
Path: dev-aws/kafka-shared-msk/iam
Commit ID: 021f1842d8083d5ec40ae0670a1ea7268239707e
Requested At: 2024-11-11T12:50:11Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan dev-aws/kafka-shared-msk/iam` as comment.

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: dev-aws
Module: pubsub/kafka-shared-msk-account-identity
Path: dev-aws/kafka-shared-msk/account-identity
Commit ID: 021f1842d8083d5ec40ae0670a1ea7268239707e
Requested At: 2024-11-11T12:50:11Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan dev-aws/kafka-shared-msk/account-identity` as comment.

**Review by abramin — APPROVED** [review]

**Comment by uw-infra** [comment]
Terraform run output for
```
Cluster: dev-aws
Module: pubsub/kafka-shared-msk-iam
Path: dev-aws/kafka-shared-msk/iam
Commit ID: 11822efd82dcb077bd8b900caf3e9d7ecb4389ea
```
<details><summary><b>✅ Run Status: Ok, Run Summary: Apply complete! Resources: 2 added, 0 changed, 0 destroyed</b></summary>

```terraform

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.account_identity_di_kafka_source_verification.kafka_acl.group_acl["account-identity.di-kafka-source-verification"] will be created
  + resource "kafka_acl" "group_acl" {
      + acl_host                     = "*"
      + acl_operation                = "Read"
      + acl_permission_type          = "Allow"
      + acl_principal                = "User:CN=auth-customer/di-verification"
      + id                           = (known after apply)
      + resource_name                = "account-identity.di-kafka-source-verification"
      + resource_pattern_type_filter = "Literal"
      + resource_type                = "Group"
    }

  # module.account_identity_di_kafka_source_verification.kafka_acl.topic_acl["auth-customer.iam-dpd-v1"] will be created
  + resource "kafka_acl" "topic_acl" {
      + acl_host                     = "*"
      + acl_operation                = "Read"
      + acl_permission_type          = "Allow"
      + acl_principal                = "User:CN=auth-customer/di-verification"
      + id                           = (known after apply)
      + resource_name                = "auth-customer.iam-dpd-v1"
      + resource_pattern_type_filter = "Literal"
      + resource_type                = "Topic"
    }

Plan: 2 to add, 0 to change, 0 to destroy.
module.account_identity_di_kafka_source_verification.kafka_acl.topic_acl["auth-customer.iam-dpd-v1"]: Creating...
module.account_identity_di_kafka_source_verification.kafka_acl.group_acl["account-identity.di-kafka-source-verification"]: Creating...
module.account_identity_di_kafka_source_verification.kafka_acl.topic_acl["auth-customer.iam-dpd-v1"]: Creation complete after 0s [id=User:CN=auth-customer/di-verification|*|Read|Allow|Topic|auth-customer.iam-dpd-v1|Literal]
module.account_identity_di_kafka_source_verification.kafka_acl.group_acl["account-identity.di-kafka-source-verification"]: Creation complete after 0s [id=User:CN=auth-customer/di-verification|*|Read|Allow|Group|account-identity.di-kafka-source-verification|Literal]

Warning: Argument is deprecated

  with provider["registry.terraform.io/mongey/kafka"],
  on __env.tf line 12, in provider "kafka":
  12: provider "kafka" {

This parameter is now deprecated and will be removed in a later release,
please use `client_cert` instead.

(and one more similar warning elsewhere)

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

```
</details>

> To manually trigger plan again please post `@terraform-applier plan dev-aws/kafka-shared-msk/iam` as comment.

**Comment by uw-infra** [comment]
Terraform run output for
```
Cluster: dev-aws
Module: pubsub/kafka-shared-msk-account-identity
Path: dev-aws/kafka-shared-msk/account-identity
Commit ID: 11822efd82dcb077bd8b900caf3e9d7ecb4389ea
```
<details><summary><b>✅ Run Status: Ok, Run Summary: Apply complete! Resources: 0 added, 0 changed, 2 destroyed</b></summary>

```terraform

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  # module.account_identity_di_kafka_source_verification.kafka_acl.group_acl["account-identity.di-kafka-source-verification"] will be destroyed
  # (because kafka_acl.group_acl is not in configuration)
  - resource "kafka_acl" "group_acl" {
      - acl_host                     = "*" -> null
      - acl_operation                = "Read" -> null
      - acl_permission_type          = "Allow" -> null
      - acl_principal                = "User:CN=auth-customer/di-verification" -> null
      - id                           = "User:CN=auth-customer/di-verification|*|Read|Allow|Group|account-identity.di-kafka-source-verification|Literal" -> null
      - resource_name                = "account-identity.di-kafka-source-verification" -> null
      - resource_pattern_type_filter = "Literal" -> null
      - resource_type                = "Group" -> null
    }

  # module.account_identity_di_kafka_source_verification.kafka_acl.topic_acl["account-identity.verification.events.v1"] will be destroyed
  # (because kafka_acl.topic_acl is not in configuration)
  - resource "kafka_acl" "topic_acl" {
      - acl_host                     = "*" -> null
      - acl_operation                = "Read" -> null
      - acl_permission_type          = "Allow" -> null
      - acl_principal                = "User:CN=auth-customer/di-verification" -> null
      - id                           = "User:CN=auth-customer/di-verification|*|Read|Allow|Topic|account-identity.verification.events.v1|Literal" -> null
      - resource_name                = "account-identity.verification.events.v1" -> null
      - resource_pattern_type_filter = "Literal" -> null
      - resource_type                = "Topic" -> null
    }

Plan: 0 to add, 0 to change, 2 to destroy.
module.account_identity_di_kafka_source_verification.kafka_acl.topic_acl["account-identity.verification.events.v1"]: Destroying... [id=User:CN=auth-customer/di-verification|*|Read|Allow|Topic|account-identity.verification.events.v1|Literal]
module.account_identity_di_kafka_source_verification.kafka_acl.group_acl["account-identity.di-kafka-source-verification"]: Destroying... [id=User:CN=auth-customer/di-verification|*|Read|Allow|Group|account-identity.di-kafka-source-verification|Literal]
module.account_identity_di_kafka_source_verification.kafka_acl.topic_acl["account-identity.verification.events.v1"]: Destruction complete after 0s
module.account_identity_di_kafka_source_verification.kafka_acl.group_acl["account-identity.di-kafka-source-verification"]: Destruction complete after 0s

Warning: Argument is deprecated

  with provider["registry.terraform.io/mongey/kafka"],
  on __env.tf line 12, in provider "kafka":
  12: provider "kafka" {

This parameter is now deprecated and will be removed in a later release,
please use `client_cert` instead.

(and one more similar warning elsewhere)

Apply complete! Resources: 0 added, 0 changed, 2 destroyed.

```
</details>

> To manually trigger plan again please post `@terraform-applier plan dev-aws/kafka-shared-msk/account-identity` as comment.

**Comment by uw-infra** [comment]
Terraform run output for
```
Cluster: prod-aws
Module: pubsub/kafka-shared-msk-account-identity
Path: prod-aws/kafka-shared-msk/account-identity
Commit ID: 11822efd82dcb077bd8b900caf3e9d7ecb4389ea
```
<details><summary><b>✅ Run Status: Ok, Run Summary: Apply complete! Resources: 0 added, 0 changed, 2 destroyed</b></summary>

```terraform

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  # module.account_identity_di_kafka_source_verification.kafka_acl.group_acl["account-identity.di-kafka-source-verification"] will be destroyed
  # (because kafka_acl.group_acl is not in configuration)
  - resource "kafka_acl" "group_acl" {
      - acl_host                     = "*" -> null
      - acl_operation                = "Read" -> null
      - acl_permission_type          = "Allow" -> null
      - acl_principal                = "User:CN=auth-customer/di-verification" -> null
      - id                           = "User:CN=auth-customer/di-verification|*|Read|Allow|Group|account-identity.di-kafka-source-verification|Literal" -> null
      - resource_name                = "account-identity.di-kafka-source-verification" -> null
      - resource_pattern_type_filter = "Literal" -> null
      - resource_type                = "Group" -> null
    }

  # module.account_identity_di_kafka_source_verification.kafka_acl.topic_acl["account-identity.verification.events.v1"] will be destroyed
  # (because kafka_acl.topic_acl is not in configuration)
  - resource "kafka_acl" "topic_acl" {
      - acl_host                     = "*" -> null
      - acl_operation                = "Read" -> null
      - acl_permission_type          = "Allow" -> null
      - acl_principal                = "User:CN=auth-customer/di-verification" -> null
      - id                           = "User:CN=auth-customer/di-verification|*|Read|Allow|Topic|account-identity.verification.events.v1|Literal" -> null
      - resource_name                = "account-identity.verification.events.v1" -> null
      - resource_pattern_type_filter = "Literal" -> null
      - resource_type                = "Topic" -> null
    }

Plan: 0 to add, 0 to change, 2 to destroy.
module.account_identity_di_kafka_source_verification.kafka_acl.topic_acl["account-identity.verification.events.v1"]: Destroying... [id=User:CN=auth-customer/di-verification|*|Read|Allow|Topic|account-identity.verification.events.v1|Literal]
module.account_identity_di_kafka_source_verification.kafka_acl.group_acl["account-identity.di-kafka-source-verification"]: Destroying... [id=User:CN=auth-customer/di-verification|*|Read|Allow|Group|account-identity.di-kafka-source-verification|Literal]
module.account_identity_di_kafka_source_verification.kafka_acl.topic_acl["account-identity.verification.events.v1"]: Destruction complete after 1s
module.account_identity_di_kafka_source_verification.kafka_acl.group_acl["account-identity.di-kafka-source-verification"]: Destruction complete after 1s

Warning: Argument is deprecated

  with provider["registry.terraform.io/mongey/kafka"],
  on __env.tf line 12, in provider "kafka":
  12: provider "kafka" {

This parameter is now deprecated and will be removed in a later release,
please use `client_key` instead.

(and one more similar warning elsewhere)

Apply complete! Resources: 0 added, 0 changed, 2 destroyed.

```
</details>

> To manually trigger plan again please post `@terraform-applier plan prod-aws/kafka-shared-msk/account-identity` as comment.

**Pull request merged**
