### PR TITLE
[DEV][FPAY-1518] Define payment method events topic and configure access

### PR DESCRIPTION
**Pull request by ggeorgiu**

### CODE REVIEW

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: dev-aws
Module: pubsub/kafka-shared-msk-payment-platform
Path: dev-aws/kafka-shared-msk/payment-platform
Commit ID: ba3d190509a6c4884a6c24e1d01c9c0c56e53582
Requested At: 2024-09-10T11:13:05Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan dev-aws/kafka-shared-msk/payment-platform` as comment.

**Comment by ggeorgiu** [comment]
@terraform-applier plan dev-aws/kafka-shared-msk/payment-platform

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: dev-aws
Module: pubsub/kafka-shared-msk-payment-platform
Path: dev-aws/kafka-shared-msk/payment-platform
Commit ID: ea89790a4f745607224e6fe6c6b9e373d1ad6614
Requested At: 2024-09-10T11:17:44Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan dev-aws/kafka-shared-msk/payment-platform` as comment.

**Review by sbuliarca — APPROVED** [review]

**Comment by ggeorgiu** [comment]
@terraform-applier plan dev-aws/kafka-shared-msk/payment-platform

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: dev-aws
Module: pubsub/kafka-shared-msk-payment-platform
Path: dev-aws/kafka-shared-msk/payment-platform
Commit ID: ea89790a4f745607224e6fe6c6b9e373d1ad6614
Requested At: 2024-09-10T12:11:04Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan dev-aws/kafka-shared-msk/payment-platform` as comment.

**Pull request merged**
