### PR TITLE
Account api now produces to more topics

### PR DESCRIPTION
**Pull request by matiit**

### CODE REVIEW

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: dev-aws
Module: pubsub/kafka-shared-msk-account-identity
Path: dev-aws/kafka-shared-msk/account-identity
Commit ID: b50205e5b43b0cda556ae505a8e42e2fcd5b6e64
Requested At: 2024-11-28T15:41:12Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan dev-aws/kafka-shared-msk/account-identity` as comment.

**Review by abramin — APPROVED** [review]

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: dev-aws
Module: pubsub/kafka-shared-msk-account-identity
Path: dev-aws/kafka-shared-msk/account-identity
Commit ID: 7331b355f55962997d76d37016d18ab1c7b625b8
Requested At: 2024-12-02T09:05:31Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan dev-aws/kafka-shared-msk/account-identity` as comment.

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: dev-aws
Module: pubsub/kafka-shared-msk-account-identity
Path: dev-aws/kafka-shared-msk/account-identity
Commit ID: a608c301dfa5dd0e119d9388bd5ac30166e561be
Requested At: 2024-12-02T09:45:05Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan dev-aws/kafka-shared-msk/account-identity` as comment.

**Review by denisnikulin — APPROVED** [review]

**Review by denisnikulin — APPROVED** [review]

**Comment by uw-infra** [comment]
Terraform run output for
```
Cluster: dev-aws
Module: pubsub/kafka-shared-msk-account-identity
Path: dev-aws/kafka-shared-msk/account-identity
Commit ID: 7d2ea049120e9c92d9f6ae8b43c9786400f3ed0a
```
<details><summary><b>✅ Run Status: Ok, Run Summary: Apply complete! Resources: 2 added, 0 changed, 1 destroyed</b></summary>

```terraform

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create
  - destroy

Terraform will perform the following actions:

  # module.account_identity_account_api.kafka_acl.producer_acl["account-identity.account.atomic.v1"] will be created
  + resource "kafka_acl" "producer_acl" {
      + acl_host                     = "*"
      + acl_operation                = "Write"
      + acl_permission_type          = "Allow"
      + acl_principal                = "User:CN=account-platform/account_api"
      + id                           = (known after apply)
      + resource_name                = "account-identity.account.atomic.v1"
      + resource_pattern_type_filter = "Literal"
      + resource_type                = "Topic"
    }

  # module.account_identity_account_api.kafka_acl.producer_acl["account-identity.account.events.v2"] will be created
  + resource "kafka_acl" "producer_acl" {
      + acl_host                     = "*"
      + acl_operation                = "Write"
      + acl_permission_type          = "Allow"
      + acl_principal                = "User:CN=account-platform/account_api"
      + id                           = (known after apply)
      + resource_name                = "account-identity.account.events.v2"
      + resource_pattern_type_filter = "Literal"
      + resource_type                = "Topic"
    }

  # module.account_identity_account_api_account_atomic_producer.kafka_acl.producer_acl["account-identity.account.atomic.v1"] will be destroyed
  # (because kafka_acl.producer_acl is not in configuration)
  - resource "kafka_acl" "producer_acl" {
      - acl_host                     = "*" -> null
      - acl_operation                = "Write" -> null
      - acl_permission_type          = "Allow" -> null
      - acl_principal                = "User:CN=account-platform/account_api_account_atomic_producer" -> null
      - id                           = "User:CN=account-platform/account_api_account_atomic_producer|*|Write|Allow|Topic|account-identity.account.atomic.v1|Literal" -> null
      - resource_name                = "account-identity.account.atomic.v1" -> null
      - resource_pattern_type_filter = "Literal" -> null
      - resource_type                = "Topic" -> null
    }

Plan: 2 to add, 0 to change, 1 to destroy.
module.account_identity_account_api_account_atomic_producer.kafka_acl.producer_acl["account-identity.account.atomic.v1"]: Destroying... [id=User:CN=account-platform/account_api_account_atomic_producer|*|Write|Allow|Topic|account-identity.account.atomic.v1|Literal]
module.account_identity_account_api.kafka_acl.producer_acl["account-identity.account.events.v2"]: Creating...
module.account_identity_account_api.kafka_acl.producer_acl["account-identity.account.atomic.v1"]: Creating...
module.account_identity_account_api_account_atomic_producer.kafka_acl.producer_acl["account-identity.account.atomic.v1"]: Destruction complete after 1s
module.account_identity_account_api.kafka_acl.producer_acl["account-identity.account.events.v2"]: Creation complete after 1s [id=User:CN=account-platform/account_api|*|Write|Allow|Topic|account-identity.account.events.v2|Literal]
module.account_identity_account_api.kafka_acl.producer_acl["account-identity.account.atomic.v1"]: Creation complete after 1s [id=User:CN=account-platform/account_api|*|Write|Allow|Topic|account-identity.account.atomic.v1|Literal]

Warning: Argument is deprecated

  with provider["registry.terraform.io/mongey/kafka"],
  on __env.tf line 12, in provider "kafka":
  12: provider "kafka" {

This parameter is now deprecated and will be removed in a later release,
please use `client_cert` instead.

(and one more similar warning elsewhere)

Apply complete! Resources: 2 added, 0 changed, 1 destroyed.

```
</details>

> To manually trigger plan again please post `@terraform-applier plan dev-aws/kafka-shared-msk/account-identity` as comment.

**Pull request merged**
