### PR TITLE
Delete account balance events compacted topic

### PR DESCRIPTION
**Pull request by danielcopaciu**

### CODE REVIEW

**Comment by tosan88** [comment]
Aren't we going to need that moving forward?

**Comment by danielcopaciu** [comment]
@tosan88 I did the reconciliation and the messages on this topic are incorrect. I plan to delete the topic, create it again and publish the messages again.

**Comment by danielcopaciu** [comment]
I could try manually deleting the topic but I'm not sure how the terraform applier will react.

**Review by tosan88 — APPROVED** [review]

**Comment by danielcopaciu** [comment]
@tosan88 Hopefully this [pull request](https://github.com/utilitywarehouse/finance-account-balance-events/pull/27/files) will bring more clarity.

**Review by lucassouzavieira — APPROVED** [review]

**Pull request merged**
