### PR TITLE
cbc: add crm services projector tls-app

### PR DESCRIPTION
**Pull request by martskins**

### CODE REVIEW

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: prod-aws
Module: pubsub/kafka-shared-msk-cbc
Path: prod-aws/kafka-shared-msk/cbc
Commit ID: 3367879d937d69407e01123953b9a0fcd7159311
Requested At: 2024-11-07T10:41:12Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan prod-aws/kafka-shared-msk/cbc` as comment.

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: dev-aws
Module: pubsub/kafka-shared-msk-cbc
Path: dev-aws/kafka-shared-msk/cbc
Commit ID: 3367879d937d69407e01123953b9a0fcd7159311
Requested At: 2024-11-07T10:41:12Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan dev-aws/kafka-shared-msk/cbc` as comment.

**Review by LukeG07 — APPROVED** [review]

**Comment by uw-infra** [comment]
Terraform run output for
```
Cluster: prod-aws
Module: pubsub/kafka-shared-msk-cbc
Path: prod-aws/kafka-shared-msk/cbc
Commit ID: 8bbcd884b3768725065f2eb40a918320f6cf061b
```
<details><summary><b>✅ Run Status: Ok, Run Summary: Apply complete! Resources: 2 added, 0 changed, 0 destroyed</b></summary>

```terraform

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.cbc_crm_services_projector.kafka_acl.group_acl["cbc.cbc-service-projector-v1"] will be created
  + resource "kafka_acl" "group_acl" {
      + acl_host                     = "*"
      + acl_operation                = "Read"
      + acl_permission_type          = "Allow"
      + acl_principal                = "User:CN=cbc/crm-services-projector"
      + id                           = (known after apply)
      + resource_name                = "cbc.cbc-service-projector-v1"
      + resource_pattern_type_filter = "Literal"
      + resource_type                = "Group"
    }

  # module.cbc_crm_services_projector.kafka_acl.topic_acl["cbc.CrmEvents"] will be created
  + resource "kafka_acl" "topic_acl" {
      + acl_host                     = "*"
      + acl_operation                = "Read"
      + acl_permission_type          = "Allow"
      + acl_principal                = "User:CN=cbc/crm-services-projector"
      + id                           = (known after apply)
      + resource_name                = "cbc.CrmEvents"
      + resource_pattern_type_filter = "Literal"
      + resource_type                = "Topic"
    }

Plan: 2 to add, 0 to change, 0 to destroy.
module.cbc_crm_services_projector.kafka_acl.group_acl["cbc.cbc-service-projector-v1"]: Creating...
module.cbc_crm_services_projector.kafka_acl.topic_acl["cbc.CrmEvents"]: Creating...
module.cbc_crm_services_projector.kafka_acl.group_acl["cbc.cbc-service-projector-v1"]: Creation complete after 0s [id=User:CN=cbc/crm-services-projector|*|Read|Allow|Group|cbc.cbc-service-projector-v1|Literal]
module.cbc_crm_services_projector.kafka_acl.topic_acl["cbc.CrmEvents"]: Creation complete after 0s [id=User:CN=cbc/crm-services-projector|*|Read|Allow|Topic|cbc.CrmEvents|Literal]

Warning: Argument is deprecated

  with provider["registry.terraform.io/mongey/kafka"],
  on __env.tf line 12, in provider "kafka":
  12: provider "kafka" {

This parameter is now deprecated and will be removed in a later release,
please use `client_cert` instead.

(and one more similar warning elsewhere)

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

```
</details>

> To manually trigger plan again please post `@terraform-applier plan prod-aws/kafka-shared-msk/cbc` as comment.

**Comment by uw-infra** [comment]
Terraform run output for
```
Cluster: dev-aws
Module: pubsub/kafka-shared-msk-cbc
Path: dev-aws/kafka-shared-msk/cbc
Commit ID: 8bbcd884b3768725065f2eb40a918320f6cf061b
```
<details><summary><b>✅ Run Status: Ok, Run Summary: Apply complete! Resources: 2 added, 0 changed, 0 destroyed</b></summary>

```terraform

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.cbc_crm_services_projector.kafka_acl.group_acl["cbc.cbc-service-projector-v1"] will be created
  + resource "kafka_acl" "group_acl" {
      + acl_host                     = "*"
      + acl_operation                = "Read"
      + acl_permission_type          = "Allow"
      + acl_principal                = "User:CN=cbc/crm-services-projector"
      + id                           = (known after apply)
      + resource_name                = "cbc.cbc-service-projector-v1"
      + resource_pattern_type_filter = "Literal"
      + resource_type                = "Group"
    }

  # module.cbc_crm_services_projector.kafka_acl.topic_acl["cbc.CrmEvents"] will be created
  + resource "kafka_acl" "topic_acl" {
      + acl_host                     = "*"
      + acl_operation                = "Read"
      + acl_permission_type          = "Allow"
      + acl_principal                = "User:CN=cbc/crm-services-projector"
      + id                           = (known after apply)
      + resource_name                = "cbc.CrmEvents"
      + resource_pattern_type_filter = "Literal"
      + resource_type                = "Topic"
    }

Plan: 2 to add, 0 to change, 0 to destroy.
module.cbc_crm_services_projector.kafka_acl.topic_acl["cbc.CrmEvents"]: Creating...
module.cbc_crm_services_projector.kafka_acl.group_acl["cbc.cbc-service-projector-v1"]: Creating...
module.cbc_crm_services_projector.kafka_acl.group_acl["cbc.cbc-service-projector-v1"]: Creation complete after 1s [id=User:CN=cbc/crm-services-projector|*|Read|Allow|Group|cbc.cbc-service-projector-v1|Literal]
module.cbc_crm_services_projector.kafka_acl.topic_acl["cbc.CrmEvents"]: Creation complete after 1s [id=User:CN=cbc/crm-services-projector|*|Read|Allow|Topic|cbc.CrmEvents|Literal]

Warning: Argument is deprecated

  with provider["registry.terraform.io/mongey/kafka"],
  on __env.tf line 12, in provider "kafka":
  12: provider "kafka" {

This parameter is now deprecated and will be removed in a later release,
please use `client_cert` instead.

(and one more similar warning elsewhere)

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

```
</details>

> To manually trigger plan again please post `@terraform-applier plan dev-aws/kafka-shared-msk/cbc` as comment.

**Pull request merged**
