### PR TITLE
Create new topic and cert for producing to it

### PR DESCRIPTION
**Pull request by matiit**

### CODE REVIEW

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: prod-aws
Module: pubsub/kafka-shared-msk-account-identity
Path: prod-aws/kafka-shared-msk/account-identity
Commit ID: 836a8ca6a16281328ff977d2b413e61166331ec1
Requested At: 2024-10-29T13:00:57Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan prod-aws/kafka-shared-msk/account-identity` as comment.

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: dev-aws
Module: pubsub/kafka-shared-msk-account-identity
Path: dev-aws/kafka-shared-msk/account-identity
Commit ID: 836a8ca6a16281328ff977d2b413e61166331ec1
Requested At: 2024-10-29T13:00:57Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan dev-aws/kafka-shared-msk/account-identity` as comment.

**Review by denisnikulin — APPROVED** [review]

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: prod-aws
Module: pubsub/kafka-shared-msk-account-identity
Path: prod-aws/kafka-shared-msk/account-identity
Commit ID: 90bd492b87bd930c539994b116dafb0eacf8cacf
Requested At: 2024-10-29T14:13:01Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan prod-aws/kafka-shared-msk/account-identity` as comment.

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: dev-aws
Module: pubsub/kafka-shared-msk-account-identity
Path: dev-aws/kafka-shared-msk/account-identity
Commit ID: 90bd492b87bd930c539994b116dafb0eacf8cacf
Requested At: 2024-10-29T14:13:02Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan dev-aws/kafka-shared-msk/account-identity` as comment.

**Review by sbuliarca — APPROVED** [review]

**Comment by uw-infra** [comment]
Terraform run output for
```
Cluster: dev-aws
Module: pubsub/kafka-shared-msk-account-identity
Path: dev-aws/kafka-shared-msk/account-identity
Commit ID: 05b5891d5d60c399234b773094f6234fca8e3a18
```
<details><summary><b>✅ Run Status: Ok, Run Summary: Apply complete! Resources: 2 added, 0 changed, 0 destroyed</b></summary>

```terraform

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # kafka_topic.account_identity_accunt_bill_writes_public will be created
  + resource "kafka_topic" "account_identity_accunt_bill_writes_public" {
      + config             = {
          + "cleanup.policy"        = "compact"
          + "compression.type"      = "zstd"
          + "max.compaction.lag.ms" = "604800000"
        }
      + id                 = (known after apply)
      + name               = "account-identity.account.bill.writes.public"
      + partitions         = 15
      + replication_factor = 3
    }

  # module.account_identity_account_api_v2.kafka_acl.producer_acl["account-identity.account.bill.writes.public"] will be created
  + resource "kafka_acl" "producer_acl" {
      + acl_host                     = "*"
      + acl_operation                = "Write"
      + acl_permission_type          = "Allow"
      + acl_principal                = "User:CN=account-platform/account_api_v2"
      + id                           = (known after apply)
      + resource_name                = "account-identity.account.bill.writes.public"
      + resource_pattern_type_filter = "Literal"
      + resource_type                = "Topic"
    }

Plan: 2 to add, 0 to change, 0 to destroy.
kafka_topic.account_identity_accunt_bill_writes_public: Creating...
kafka_topic.account_identity_accunt_bill_writes_public: Creation complete after 2s [id=account-identity.account.bill.writes.public]
module.account_identity_account_api_v2.kafka_acl.producer_acl["account-identity.account.bill.writes.public"]: Creating...
module.account_identity_account_api_v2.kafka_acl.producer_acl["account-identity.account.bill.writes.public"]: Creation complete after 0s [id=User:CN=account-platform/account_api_v2|*|Write|Allow|Topic|account-identity.account.bill.writes.public|Literal]

Warning: Argument is deprecated

  with provider["registry.terraform.io/mongey/kafka"],
  on __env.tf line 12, in provider "kafka":
  12: provider "kafka" {

This parameter is now deprecated and will be removed in a later release,
please use `client_cert` instead.

(and one more similar warning elsewhere)

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

```
</details>

> To manually trigger plan again please post `@terraform-applier plan dev-aws/kafka-shared-msk/account-identity` as comment.

**Pull request merged**
