### PR TITLE
Add tls-apps for cbc bill integration consumers

### PR DESCRIPTION
**Pull request by martskins**

### CODE REVIEW

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: prod-aws
Module: pubsub/kafka-shared-msk-cbc
Path: prod-aws/kafka-shared-msk/cbc
Commit ID: 31bb9bf1f4a5438698be72d2a47c02f873fb3adc
Requested At: 2024-11-06T13:36:24Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan prod-aws/kafka-shared-msk/cbc` as comment.

**Comment by uw-infra** [comment]
Received terraform plan request
```
Cluster: dev-aws
Module: pubsub/kafka-shared-msk-cbc
Path: dev-aws/kafka-shared-msk/cbc
Commit ID: 31bb9bf1f4a5438698be72d2a47c02f873fb3adc
Requested At: 2024-11-06T13:36:24Z
```
Do not edit this comment. This message will be updated once the plan run is completed.
To manually trigger plan again please post `@terraform-applier plan dev-aws/kafka-shared-msk/cbc` as comment.

**Review by LukeG07 — APPROVED** [review]

**Comment by uw-infra** [comment]
Terraform run output for
```
Cluster: prod-aws
Module: pubsub/kafka-shared-msk-cbc
Path: prod-aws/kafka-shared-msk/cbc
Commit ID: 6f2581adb7cf24d5992c4986a59f70cf7c8d6de4
```
<details><summary><b>✅ Run Status: Ok, Run Summary: Apply complete! Resources: 6 added, 0 changed, 0 destroyed</b></summary>

```terraform

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.cbc_bill_integration_consumer.kafka_acl.group_acl["cbc.cbc-bill-integration-consumer-v2"] will be created
  + resource "kafka_acl" "group_acl" {
      + acl_host                     = "*"
      + acl_operation                = "Read"
      + acl_permission_type          = "Allow"
      + acl_principal                = "User:CN=cbc/cbc-bill-integration-consumer"
      + id                           = (known after apply)
      + resource_name                = "cbc.cbc-bill-integration-consumer-v2"
      + resource_pattern_type_filter = "Literal"
      + resource_type                = "Group"
    }

  # module.cbc_bill_integration_consumer.kafka_acl.topic_acl["cbc.LifecycleEvents_v2"] will be created
  + resource "kafka_acl" "topic_acl" {
      + acl_host                     = "*"
      + acl_operation                = "Read"
      + acl_permission_type          = "Allow"
      + acl_principal                = "User:CN=cbc/cbc-bill-integration-consumer"
      + id                           = (known after apply)
      + resource_name                = "cbc.LifecycleEvents_v2"
      + resource_pattern_type_filter = "Literal"
      + resource_type                = "Topic"
    }

  # module.cbc_bill_integration_consumer.kafka_acl.topic_acl["cbc.legacy.account.events.v2"] will be created
  + resource "kafka_acl" "topic_acl" {
      + acl_host                     = "*"
      + acl_operation                = "Read"
      + acl_permission_type          = "Allow"
      + acl_principal                = "User:CN=cbc/cbc-bill-integration-consumer"
      + id                           = (known after apply)
      + resource_name                = "cbc.legacy.account.events.v2"
      + resource_pattern_type_filter = "Literal"
      + resource_type                = "Topic"
    }

  # module.cbc_bill_integration_projector.kafka_acl.group_acl["cbc.cbc-bill-integration-projector-v2"] will be created
  + resource "kafka_acl" "group_acl" {
      + acl_host                     = "*"
      + acl_operation                = "Read"
      + acl_permission_type          = "Allow"
      + acl_principal                = "User:CN=cbc/cbc-bill-integration-projector"
      + id                           = (known after apply)
      + resource_name                = "cbc.cbc-bill-integration-projector-v2"
      + resource_pattern_type_filter = "Literal"
      + resource_type                = "Group"
    }

  # module.cbc_bill_integration_projector.kafka_acl.topic_acl["cbc.LifecycleEvents_v2"] will be created
  + resource "kafka_acl" "topic_acl" {
      + acl_host                     = "*"
      + acl_operation                = "Read"
      + acl_permission_type          = "Allow"
      + acl_principal                = "User:CN=cbc/cbc-bill-integration-projector"
      + id                           = (known after apply)
      + resource_name                = "cbc.LifecycleEvents_v2"
      + resource_pattern_type_filter = "Literal"
      + resource_type                = "Topic"
    }

  # module.cbc_bill_integration_projector.kafka_acl.topic_acl["cbc.legacy.account.events.v2"] will be created
  + resource "kafka_acl" "topic_acl" {
      + acl_host                     = "*"
      + acl_operation                = "Read"
      + acl_permission_type          = "Allow"
      + acl_principal                = "User:CN=cbc/cbc-bill-integration-projector"
      + id                           = (known after apply)
      + resource_name                = "cbc.legacy.account.events.v2"
      + resource_pattern_type_filter = "Literal"
      + resource_type                = "Topic"
    }

Plan: 6 to add, 0 to change, 0 to destroy.
module.cbc_bill_integration_projector.kafka_acl.topic_acl["cbc.LifecycleEvents_v2"]: Creating...
module.cbc_bill_integration_consumer.kafka_acl.topic_acl["cbc.LifecycleEvents_v2"]: Creating...
module.cbc_bill_integration_projector.kafka_acl.group_acl["cbc.cbc-bill-integration-projector-v2"]: Creating...
module.cbc_bill_integration_consumer.kafka_acl.group_acl["cbc.cbc-bill-integration-consumer-v2"]: Creating...
module.cbc_bill_integration_consumer.kafka_acl.topic_acl["cbc.legacy.account.events.v2"]: Creating...
module.cbc_bill_integration_projector.kafka_acl.topic_acl["cbc.legacy.account.events.v2"]: Creating...
module.cbc_bill_integration_projector.kafka_acl.topic_acl["cbc.legacy.account.events.v2"]: Creation complete after 0s [id=User:CN=cbc/cbc-bill-integration-projector|*|Read|Allow|Topic|cbc.legacy.account.events.v2|Literal]
module.cbc_bill_integration_consumer.kafka_acl.topic_acl["cbc.LifecycleEvents_v2"]: Creation complete after 0s [id=User:CN=cbc/cbc-bill-integration-consumer|*|Read|Allow|Topic|cbc.LifecycleEvents_v2|Literal]
module.cbc_bill_integration_projector.kafka_acl.topic_acl["cbc.LifecycleEvents_v2"]: Creation complete after 0s [id=User:CN=cbc/cbc-bill-integration-projector|*|Read|Allow|Topic|cbc.LifecycleEvents_v2|Literal]
module.cbc_bill_integration_consumer.kafka_acl.group_acl["cbc.cbc-bill-integration-consumer-v2"]: Creation complete after 0s [id=User:CN=cbc/cbc-bill-integration-consumer|*|Read|Allow|Group|cbc.cbc-bill-integration-consumer-v2|Literal]
module.cbc_bill_integration_consumer.kafka_acl.topic_acl["cbc.legacy.account.events.v2"]: Creation complete after 0s [id=User:CN=cbc/cbc-bill-integration-consumer|*|Read|Allow|Topic|cbc.legacy.account.events.v2|Literal]
module.cbc_bill_integration_projector.kafka_acl.group_acl["cbc.cbc-bill-integration-projector-v2"]: Creation complete after 0s [id=User:CN=cbc/cbc-bill-integration-projector|*|Read|Allow|Group|cbc.cbc-bill-integration-projector-v2|Literal]

Warning: Argument is deprecated

  with provider["registry.terraform.io/mongey/kafka"],
  on __env.tf line 12, in provider "kafka":
  12: provider "kafka" {

This parameter is now deprecated and will be removed in a later release,
please use `client_key` instead.

(and one more similar warning elsewhere)

Apply complete! Resources: 6 added, 0 changed, 0 destroyed.

```
</details>

> To manually trigger plan again please post `@terraform-applier plan prod-aws/kafka-shared-msk/cbc` as comment.

**Comment by uw-infra** [comment]
Terraform run output for
```
Cluster: dev-aws
Module: pubsub/kafka-shared-msk-cbc
Path: dev-aws/kafka-shared-msk/cbc
Commit ID: 6f2581adb7cf24d5992c4986a59f70cf7c8d6de4
```
<details><summary><b>✅ Run Status: Ok, Run Summary: Apply complete! Resources: 6 added, 0 changed, 0 destroyed</b></summary>

```terraform

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.cbc_bill_integration_consumer.kafka_acl.group_acl["cbc.cbc-bill-integration-consumer-v2"] will be created
  + resource "kafka_acl" "group_acl" {
      + acl_host                     = "*"
      + acl_operation                = "Read"
      + acl_permission_type          = "Allow"
      + acl_principal                = "User:CN=cbc/cbc-bill-integration-consumer"
      + id                           = (known after apply)
      + resource_name                = "cbc.cbc-bill-integration-consumer-v2"
      + resource_pattern_type_filter = "Literal"
      + resource_type                = "Group"
    }

  # module.cbc_bill_integration_consumer.kafka_acl.topic_acl["cbc.LifecycleEvents_v2"] will be created
  + resource "kafka_acl" "topic_acl" {
      + acl_host                     = "*"
      + acl_operation                = "Read"
      + acl_permission_type          = "Allow"
      + acl_principal                = "User:CN=cbc/cbc-bill-integration-consumer"
      + id                           = (known after apply)
      + resource_name                = "cbc.LifecycleEvents_v2"
      + resource_pattern_type_filter = "Literal"
      + resource_type                = "Topic"
    }

  # module.cbc_bill_integration_consumer.kafka_acl.topic_acl["cbc.legacy.account.events.v2"] will be created
  + resource "kafka_acl" "topic_acl" {
      + acl_host                     = "*"
      + acl_operation                = "Read"
      + acl_permission_type          = "Allow"
      + acl_principal                = "User:CN=cbc/cbc-bill-integration-consumer"
      + id                           = (known after apply)
      + resource_name                = "cbc.legacy.account.events.v2"
      + resource_pattern_type_filter = "Literal"
      + resource_type                = "Topic"
    }

  # module.cbc_bill_integration_projector.kafka_acl.group_acl["cbc.cbc-bill-integration-projector-v2"] will be created
  + resource "kafka_acl" "group_acl" {
      + acl_host                     = "*"
      + acl_operation                = "Read"
      + acl_permission_type          = "Allow"
      + acl_principal                = "User:CN=cbc/cbc-bill-integration-projector"
      + id                           = (known after apply)
      + resource_name                = "cbc.cbc-bill-integration-projector-v2"
      + resource_pattern_type_filter = "Literal"
      + resource_type                = "Group"
    }

  # module.cbc_bill_integration_projector.kafka_acl.topic_acl["cbc.LifecycleEvents_v2"] will be created
  + resource "kafka_acl" "topic_acl" {
      + acl_host                     = "*"
      + acl_operation                = "Read"
      + acl_permission_type          = "Allow"
      + acl_principal                = "User:CN=cbc/cbc-bill-integration-projector"
      + id                           = (known after apply)
      + resource_name                = "cbc.LifecycleEvents_v2"
      + resource_pattern_type_filter = "Literal"
      + resource_type                = "Topic"
    }

  # module.cbc_bill_integration_projector.kafka_acl.topic_acl["cbc.legacy.account.events.v2"] will be created
  + resource "kafka_acl" "topic_acl" {
      + acl_host                     = "*"
      + acl_operation                = "Read"
      + acl_permission_type          = "Allow"
      + acl_principal                = "User:CN=cbc/cbc-bill-integration-projector"
      + id                           = (known after apply)
      + resource_name                = "cbc.legacy.account.events.v2"
      + resource_pattern_type_filter = "Literal"
      + resource_type                = "Topic"
    }

Plan: 6 to add, 0 to change, 0 to destroy.
module.cbc_bill_integration_consumer.kafka_acl.group_acl["cbc.cbc-bill-integration-consumer-v2"]: Creating...
module.cbc_bill_integration_projector.kafka_acl.topic_acl["cbc.LifecycleEvents_v2"]: Creating...
module.cbc_bill_integration_projector.kafka_acl.topic_acl["cbc.legacy.account.events.v2"]: Creating...
module.cbc_bill_integration_consumer.kafka_acl.topic_acl["cbc.legacy.account.events.v2"]: Creating...
module.cbc_bill_integration_projector.kafka_acl.group_acl["cbc.cbc-bill-integration-projector-v2"]: Creating...
module.cbc_bill_integration_consumer.kafka_acl.topic_acl["cbc.LifecycleEvents_v2"]: Creating...
module.cbc_bill_integration_projector.kafka_acl.group_acl["cbc.cbc-bill-integration-projector-v2"]: Creation complete after 1s [id=User:CN=cbc/cbc-bill-integration-projector|*|Read|Allow|Group|cbc.cbc-bill-integration-projector-v2|Literal]
module.cbc_bill_integration_consumer.kafka_acl.topic_acl["cbc.legacy.account.events.v2"]: Creation complete after 1s [id=User:CN=cbc/cbc-bill-integration-consumer|*|Read|Allow|Topic|cbc.legacy.account.events.v2|Literal]
module.cbc_bill_integration_consumer.kafka_acl.topic_acl["cbc.LifecycleEvents_v2"]: Creation complete after 1s [id=User:CN=cbc/cbc-bill-integration-consumer|*|Read|Allow|Topic|cbc.LifecycleEvents_v2|Literal]
module.cbc_bill_integration_projector.kafka_acl.topic_acl["cbc.LifecycleEvents_v2"]: Creation complete after 1s [id=User:CN=cbc/cbc-bill-integration-projector|*|Read|Allow|Topic|cbc.LifecycleEvents_v2|Literal]
module.cbc_bill_integration_projector.kafka_acl.topic_acl["cbc.legacy.account.events.v2"]: Creation complete after 1s [id=User:CN=cbc/cbc-bill-integration-projector|*|Read|Allow|Topic|cbc.legacy.account.events.v2|Literal]
module.cbc_bill_integration_consumer.kafka_acl.group_acl["cbc.cbc-bill-integration-consumer-v2"]: Creation complete after 1s [id=User:CN=cbc/cbc-bill-integration-consumer|*|Read|Allow|Group|cbc.cbc-bill-integration-consumer-v2|Literal]

Warning: Argument is deprecated

  with provider["registry.terraform.io/mongey/kafka"],
  on __env.tf line 12, in provider "kafka":
  12: provider "kafka" {

This parameter is now deprecated and will be removed in a later release,
please use `client_cert` instead.

(and one more similar warning elsewhere)

Apply complete! Resources: 6 added, 0 changed, 0 destroyed.

```
</details>

> To manually trigger plan again please post `@terraform-applier plan dev-aws/kafka-shared-msk/cbc` as comment.

**Pull request merged**
